spring:
  datasource:
    name: ckgl
    url: jdbc:mysql://**********/ckgl
    username: ****
    password: ********
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.Gallifrey.springboot00.bean


server:
  port: 9001